title: "Vac Protocol"

markdown: kramdown
theme: minima

collections:
  specs:
    output: true
    permalink: /:path

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

header_pages:
  - waku.md
